name: gfx803
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - https://github.com/xuhuisheng/rocm-gfx803/releases/download/rocm500/torch-1.11.0a0+git503a092-cp38-cp38-linux_x86_64.whl
    - https://github.com/xuhuisheng/rocm-gfx803/releases/download/rocm500/torchvision-0.12.0a0+2662797-cp38-cp38-linux_x86_64.whl
    - https://github.com/xuhuisheng/rocm-gfx803/releases/download/rocm510/torchaudio-0.11.0+820b383-cp38-cp38-linux_x86_64.whl
    - https://github.com/xuhuisheng/rocm-gfx803/releases/download/rocm500/tensorflow_rocm-2.8.0-cp38-cp38-linux_x86_64.whl
